module  -- shake: keep-all --deprecated_module: ignore

public import QuadraticIterates.ArchMath1992
public import QuadraticIterates.ArchMath1992.DegreeCriterion
public import QuadraticIterates.ArchMath1992.Irreducibility
public import QuadraticIterates.ArchMath1992.Iterates
public import QuadraticIterates.ArchMath1992.Main
public import QuadraticIterates.ArchMath1992.Sequences
public import QuadraticIterates.Li
public import QuadraticIterates.Li.ArchMath2020
public import QuadraticIterates.Li.ArchMath2021
public import QuadraticIterates.Li.Residues
public import QuadraticIterates.Mathlib.Algebra.BigOperators
public import QuadraticIterates.Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import QuadraticIterates.Mathlib.Algebra.BigOperators.GroupWithZero.Finset
public import QuadraticIterates.Mathlib.Algebra.GCDMonoid.Basic
public import QuadraticIterates.Mathlib.Algebra.Group.Subgroup.Ker
public import QuadraticIterates.Mathlib.Algebra.Polynomial.EvenComp
public import QuadraticIterates.Mathlib.Algebra.Polynomial.FieldDivision
public import QuadraticIterates.Mathlib.Algebra.Polynomial.Roots
public import QuadraticIterates.Mathlib.Algebra.Squares
public import QuadraticIterates.Mathlib.Data.Fintype.Basic
public import QuadraticIterates.Mathlib.Data.Int.Order.Units
public import QuadraticIterates.Mathlib.Data.Multiset
public import QuadraticIterates.Mathlib.Data.ZMod
public import QuadraticIterates.Mathlib.FieldTheory.Multiquadratic
public import QuadraticIterates.Mathlib.FieldTheory.PolynomialGaloisGroup
public import QuadraticIterates.Mathlib.GroupTheory.Card
public import QuadraticIterates.Mathlib.GroupTheory.PGroup
public import QuadraticIterates.Mathlib.GroupTheory.RegularWreathProduct
public import QuadraticIterates.Mathlib.LinearAlgebra.Dimension.OrzechProperty
public import QuadraticIterates.Mathlib.LinearAlgebra.Pi
public import QuadraticIterates.Mathlib.NumberTheory.Moebius
public import QuadraticIterates.Mathlib.RingTheory.Localization.Away.Basic
public import QuadraticIterates.Mathlib.RingTheory.Localization.Basic
public import QuadraticIterates.Mathlib.RingTheory.MoebiusFactor
public import QuadraticIterates.Mathlib.RingTheory.PrincipalIdealDomain
public import QuadraticIterates.Mathlib.RingTheory.Radical.NatInt
public import QuadraticIterates.Mathlib.RingTheory.UniqueFactorizationDomain
public import QuadraticIterates.Rational
public import QuadraticIterates.Rational.GammaTwo
public import QuadraticIterates.Rational.Reflection
public import QuadraticIterates.Rational.Residues
public import QuadraticIterates.Rational.Sequence
