/-
Copyright (c) 2026 Michael Stoll. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael Stoll
-/
module

public import Mathlib.FieldTheory.PolynomialGaloisGroup
public import Mathlib.GroupTheory.RegularWreathProduct
public import QuadraticIterates.ArchMath1992.Sequences
public import QuadraticIterates.Mathlib.FieldTheory.Multiquadratic

import QuadraticIterates.Mathlib.Algebra.BigOperators
import QuadraticIterates.Mathlib.FieldTheory.PolynomialGaloisGroup
import QuadraticIterates.Mathlib.GroupTheory.Card
import QuadraticIterates.Mathlib.GroupTheory.RegularWreathProduct

/-!
# The iterates of `X² + a`, their splitting fields and Galois groups

The iterates `f_n` of `f = X² + a`, the splitting field `K_n` of `f_n` over `ℚ` taken inside
`AlgebraicClosure ℚ`, the Galois group `Ω_n = Gal(f_n/ℚ)` and the iterated wreath product `[C₂]ⁿ`;
the integer sequences `c_n` and `b_n` and the rescaled polynomial `normPoly a`; 2-independence of
families of rationals. The main results here are Odoni's embedding `Ω_n ↪ [C₂]ⁿ`
(`odoni_embedding`), the Kummer tower `K_n ⊆ K_{n+1}` with `[K_{n+1} : K_n] ≤ 2^{2^n}`
(`splittingField_succ_eq_sup_adjoin`, `relfinrank_succ_le`), and Lemma 1.4
(`nonempty_mulEquiv_succ_iff`).

Part of the formalization of M. Stoll, *Galois groups over ℚ of some iterated polynomials*,
Arch. Math. **59** (1992), 239-244; see `QuadraticIterates.ArchMath1992`.

## Notation

`fℚ[a, n]` is scoped notation for the iterate `f_n` viewed in `ℚ[X]`.
-/

@[expose] public section

open Polynomial

namespace QuadraticIterates

/-- The iterates `f_n` of `f = X² + a` over a commutative (semi)ring `R`: `f_0 = X`,
`f_{n+1} = f_n² + a`. Over `ℤ` (`R := ℤ`) this is the sequence of the paper. -/
noncomputable def iteratedPoly {R : Type*} [CommSemiring R] (a : R) : ℕ → R[X]
  | 0 => X
  | n + 1 => (iteratedPoly a n) ^ 2 + C a

@[simp] lemma iteratedPoly_zero {R : Type*} [CommSemiring R] (a : R) : iteratedPoly a 0 = X := rfl

lemma iteratedPoly_succ {R : Type*} [CommSemiring R] (a : R) (n : ℕ) :
    iteratedPoly a (n + 1) = iteratedPoly a n ^ 2 + C a := rfl

/-- Iterating commutes with any ring homomorphism: the image of `f_n` under `φ` is the `n`-th
iterate over the codomain with parameter `φ a`. -/
lemma map_iteratedPoly {R S : Type*} [CommSemiring R] [CommSemiring S] (φ : R →+* S) (a : R)
    (n : ℕ) : (iteratedPoly a n).map φ = iteratedPoly (φ a) n := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [iteratedPoly_succ, Polynomial.map_add, Polynomial.map_pow, ih, map_C, iteratedPoly_succ]

/-- `f_{n+1} = f_n ∘ (X² + a)`: the iterate can also grow on the right. -/
lemma iteratedPoly_succ_comp {R : Type*} [CommSemiring R] (a : R) (n : ℕ) :
    iteratedPoly a (n + 1) = (iteratedPoly a n).comp (X ^ 2 + C a) := by
  induction n with
  | zero => simp [iteratedPoly_succ]
  | succ k ih =>
    rw [iteratedPoly_succ a (k + 1)]
    nth_rw 1 [ih]
    rw [iteratedPoly_succ, add_comp, pow_comp, C_comp]

/-- Iterates compose additively: `f_{m+n} = f_m ∘ f_n`. -/
lemma iteratedPoly_add {R : Type*} [CommSemiring R] (a : R) (m n : ℕ) :
    iteratedPoly a (m + n) = (iteratedPoly a m).comp (iteratedPoly a n) := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [show m + (k + 1) = (m + k) + 1 from rfl, iteratedPoly_succ_comp, ih, comp_assoc,
      ← iteratedPoly_succ_comp]

lemma monic_iteratedPoly {R : Type*} [CommSemiring R] [Nontrivial R] (a : R) (n : ℕ) :
    (iteratedPoly a n).Monic := by
  induction n with
  | zero => exact monic_X
  | succ k ih =>
    rw [iteratedPoly_succ_comp]
    exact ih.comp (monic_X_pow_add_C a two_ne_zero) (by simp)

lemma natDegree_iteratedPoly {R : Type*} [CommSemiring R] [NoZeroDivisors R] [Nontrivial R]
    (a : R) (n : ℕ) : (iteratedPoly a n).natDegree = 2 ^ n := by
  induction n with
  | zero => simp
  | succ k ih => rw [iteratedPoly_succ_comp, natDegree_comp, ih, natDegree_X_pow_add_C, pow_succ]

/-- `fℚ[a, n]` denotes the `n`-th iterate `f_n = iteratedPoly a n`, viewed in `ℚ[X]`. -/
scoped notation "fℚ[" a ", " n "]" => map (Int.castRingHom ℚ) (iteratedPoly a n)

/-- The splitting field `K_n` of `f_n` over `ℚ`, as the intermediate field of `AlgebraicClosure ℚ`
generated by the roots of `f_n`. -/
noncomputable abbrev splittingField (a : ℤ) (n : ℕ) : IntermediateField ℚ (AlgebraicClosure ℚ) :=
  IntermediateField.adjoin ℚ ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ))

instance splittingField.instIsSplittingField (a : ℤ) (n : ℕ) :
    IsSplittingField ℚ ↥(splittingField a n) (fℚ[a, n]) :=
  IntermediateField.adjoin_rootSet_isSplittingField (IsAlgClosed.splits _)

instance splittingField.instFiniteDimensional (a : ℤ) (n : ℕ) :
    FiniteDimensional ℚ ↥(splittingField a n) :=
  IsSplittingField.finiteDimensional _ (fℚ[a, n])

instance splittingField.instIsGalois (a : ℤ) (n : ℕ) : IsGalois ℚ ↥(splittingField a n) :=
  have : Normal ℚ ↥(splittingField a n) := Normal.of_isSplittingField (fℚ[a, n])
  IsGalois.mk

/-- The Galois group `Ω_n = Gal(f_n/ℚ)` of the `n`-th iterate, via Mathlib's `Polynomial.Gal`. -/
noncomputable abbrev GaloisGroup (a : ℤ) (n : ℕ) : Type := (fℚ[a, n]).Gal

/-- The `n`-fold iterated regular wreath product `[C_2]^n` of `C_2 = Multiplicative (ZMod 2)`, via
Mathlib's `IteratedWreathProduct`. -/
abbrev WreathPower (n : ℕ) : Type := IteratedWreathProduct (Multiplicative (ZMod 2)) n
/-! ### The sequences `c` and `b` over `ℤ` -/

/-- `X² + a` is an even polynomial. -/
lemma evenPoly_X_sq_add_C {R : Type*} [CommSemiring R] (a : R) : EvenPoly (X ^ 2 + C a) :=
  ⟨X + C a, by rw [map_add, expand_X, expand_C]⟩

/-- `b·X² + c` is an even polynomial. -/
lemma evenPoly_C_mul_X_sq_add_C {R : Type*} [CommSemiring R] (b c : R) :
    EvenPoly (C b * X ^ 2 + C c) :=
  ⟨C b * X + C c, by simp⟩

/-- The integer sequence `c_n` (indexed from 1): `c_1 = -a`, `c_{n+1} = c_n² + a`; the value at
index `0` is `0`. It is the `γ`-sequence of `X² + a` with `ε = -1`. -/
noncomputable def cSeq (a : ℤ) : ℕ → ℤ := gammaSeq (X ^ 2 + C a) (-1)

/-- `c_n = γ_n(X² + a, ε = -1)` (definitional). -/
lemma cSeq_eq_gammaSeq (a : ℤ) (n : ℕ) : cSeq a n = gammaSeq (X ^ 2 + C a) (-1) n := rfl

@[simp] lemma cSeq_zero (a : ℤ) : cSeq a 0 = 0 := rfl

@[simp] lemma cSeq_one (a : ℤ) : cSeq a 1 = -a := by simp [cSeq_eq_gammaSeq]

/-- The recursion `c_{n+1} = c_n² + a`, valid for `n ≥ 1`. -/
theorem cSeq_succ (a : ℤ) {n : ℕ} (hn : 1 ≤ n) : cSeq a (n + 1) = cSeq a n ^ 2 + a := by
  simp only [cSeq_eq_gammaSeq, gammaSeq_succ _ _ hn, eval_add, eval_pow, eval_X, eval_C]

lemma cSeq_two (a : ℤ) : cSeq a 2 = a ^ 2 + a := by rw [cSeq_succ a le_rfl, cSeq_one]; ring

/-- **Strong divisibility** for the `c`-sequence: `gcd (c_m) (c_n) = |c_{gcd m n}|`. -/
theorem cSeq_gcd (a : ℤ) (m n : ℕ) : Int.gcd (cSeq a m) (cSeq a n) = (cSeq a (m.gcd n)).natAbs :=
  gammaSeq_gcd (evenPoly_X_sq_add_C a) neg_one_sq m n

/-- Strong divisibility of the `c`-sequence in the `Associated`-of-`gcd` form consumed by the
`moebiusFactorR` API. -/
theorem cSeq_associated_gcd (a : ℤ) (m n : ℕ) :
    Associated (gcd (cSeq a m) (cSeq a n)) (cSeq a (m.gcd n)) :=
  gammaSeq_associated_gcd (evenPoly_X_sq_add_C a) neg_one_sq m n

/-- `c_{k+1} = (-1)^{2^k} · f_k(a)`; in particular `c_{k+1} = f_k(a)` for `k ≥ 1`. -/
theorem cSeq_succ_eq_neg_one_pow_mul_eval (a : ℤ) (k : ℕ) :
    cSeq a (k + 1) = (-1 : ℤ) ^ 2 ^ k * (iteratedPoly a k).eval a := by
  induction k with
  | zero => simp [cSeq_one]
  | succ i ih =>
    have hsq : ((-1 : ℤ) ^ 2 ^ i) ^ 2 = 1 := by rw [pow_right_comm, neg_one_sq, one_pow]
    have hone : (-1 : ℤ) ^ 2 ^ (i + 1) = 1 :=
      (Nat.even_pow.mpr ⟨even_two, i.succ_ne_zero⟩).neg_one_pow
    rw [cSeq_succ a (by lia), ih, hone, one_mul, mul_pow, hsq, one_mul]
    simp [iteratedPoly_succ]

/-- The Möbius factors `b_n = ∏_{d ∣ n} c_d^{μ(n/d)} ∈ ℤ` of the `c`-sequence: the specialization
of the general `β`-sequence to `X² + a`, `ε = -1` (an integer by strong divisibility, see
`intCast_bSeq`). -/
noncomputable def bSeq (a : ℤ) (n : ℕ) : ℤ := betaSeq (X ^ 2 + C a) (-1) n

lemma bSeq_eq_moebiusFactorR (a : ℤ) (n : ℕ) : bSeq a n = moebiusFactorR (cSeq a) n := rfl

@[simp] lemma bSeq_one (a : ℤ) : bSeq a 1 = -a := by
  rw [bSeq_eq_moebiusFactorR, moebiusFactorR_one, cSeq_one]

/-- The rescaling `|a|·X² + sign a` of `X² + a`. Substituting `x ↦ |a|·x` turns the recursion
`c_{n+1} = c_n² + a` into the `γ`-recursion of `normPoly a`, whose sequence is therefore
`|c_n| / |a|` (`abs_cSeq_eq_gammaSeq_mul_abs`) — in particular positive, which is what
Lemma 2.2 needs and `X² + a` itself does not provide. -/
noncomputable def normPoly (a : ℤ) : ℤ[X] := C |a| * X ^ 2 + C a.sign

@[simp] lemma eval_normPoly (a x : ℤ) : (normPoly a).eval x = |a| * x ^ 2 + a.sign := by
  simp [normPoly]

lemma evenPoly_normPoly (a : ℤ) : EvenPoly (normPoly a) := evenPoly_C_mul_X_sq_add_C |a| a.sign

/-! ### 2-independence -/

section TwoIndependent

variable {ι : Type*}

/-- A family of elements of a commutative monoid is *2-independent* if no nonempty subfamily has
a square product. For nonzero rationals this says that the classes in `ℚ*/(ℚ*)²` are
`𝔽₂`-linearly independent (`twoIndependent_iff_linearIndependent`). -/
def TwoIndependent {M : Type*} [CommMonoid M] (v : ι → M) : Prop :=
  ∀ S : Finset ι, S.Nonempty → ¬IsSquare (∏ i ∈ S, v i)

/-- The members of a 2-independent family are nonzero, `0` being a square. -/
lemma TwoIndependent.ne_zero {M : Type*} [CommMonoidWithZero M] {v : ι → M}
    (h : TwoIndependent v) (i : ι) : v i ≠ 0 :=
  fun hi ↦ h {i} (Finset.singleton_nonempty i) (by simp [hi])

/-- 2-independence of `Fin.snoc v c` restricts to the initial family `v`. -/
theorem TwoIndependent.of_snoc {M : Type*} [CommMonoid M] {n : ℕ} {v : Fin n → M} {c : M}
    (h : TwoIndependent (Fin.snoc v c)) : TwoIndependent v := fun S hS ↦ by
  simpa [Fin.snoc_castSucc, Finset.prod_map S Fin.castSuccEmb (Fin.snoc v c)] using
    h (S.map Fin.castSuccEmb) hS.map

/-- A family in a field `L` is 2-independent iff the family of its classes in `Lˣ/(Lˣ)²` is
`𝔽₂`-linearly independent. -/
theorem twoIndependent_iff_linearIndependent [Fintype ι] {L : Type*} [Field L] [DecidableEq L]
    (v : ι → L) : TwoIndependent v ↔ LinearIndependent (ZMod 2) (fun i ↦ sqClass (v i)) := by
  refine ⟨fun h ↦ Fintype.linearIndependent_iff.mpr fun g hg i ↦ ?_, fun H S hS hsq ↦ ?_⟩
  · by_contra hgi
    refine h {j | g j = 1} ⟨i, by simpa using (show ∀ x : ZMod 2, x ≠ 0 → x = 1 by decide) _ hgi⟩ ?_
    rw [isSquare_prod_iff_sum_sqClass_eq_zero (fun i _ ↦ h.ne_zero i),
      ← Finset.sum_zmod_two_smul_eq_sum_filter (fun i ↦ sqClass (v i)) g, hg]
  · classical
    have hv0 (i) : v i ≠ 0 := fun hvi ↦ H.ne_zero i (by rw [hvi, sqClass_zero])
    obtain ⟨i, hiS⟩ := hS
    refine absurd (Fintype.linearIndependent_iff.mp H (fun j ↦ if j ∈ S then 1 else 0) ?_ i)
      (by simp [hiS])
    rw [Finset.sum_zmod_two_smul_eq_sum_filter (fun j ↦ sqClass (v j)),
      show Finset.univ.filter (fun j ↦ (if j ∈ S then (1 : ZMod 2) else 0) = 1) = S by ext; simp,
      ← isSquare_prod_iff_sum_sqClass_eq_zero (fun i _ ↦ hv0 i)]
    exact hsq

end TwoIndependent


section

variable (a : ℤ)

/-! ### Degrees, roots and the Galois group of the iterates over `ℚ` -/

lemma map_iteratedPoly_succ_eq_sq_add (k : ℕ) : fℚ[a, k + 1] = (fℚ[a, k]) ^ 2 + C (a : ℚ) := by
  simp [iteratedPoly_succ]

lemma map_iteratedPoly_one : fℚ[a, 1] = X ^ 2 + C (a : ℚ) := by
  simp [map_iteratedPoly_succ_eq_sq_add]

lemma map_iteratedPoly_succ (k : ℕ) : fℚ[a, k + 1] = (fℚ[a, k]).comp (X ^ 2 + C (a : ℚ)) := by
  rw [map_iteratedPoly, map_iteratedPoly, iteratedPoly_succ_comp]; rfl

lemma monic_map_iteratedPoly (n : ℕ) : (fℚ[a, n]).Monic := by
  rw [map_iteratedPoly]; exact monic_iteratedPoly _ n

lemma natDegree_map_iteratedPoly (n : ℕ) : (fℚ[a, n]).natDegree = 2 ^ n := by
  rw [map_iteratedPoly, natDegree_iteratedPoly]

lemma ncard_rootSet_iteratedPoly_le (n : ℕ) :
    ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)).ncard ≤ 2 ^ n :=
  (ncard_rootSet_le _ _).trans_eq (natDegree_map_iteratedPoly a n)

lemma mem_rootSet_iteratedPoly_succ (n : ℕ) (β : AlgebraicClosure ℚ) :
    β ∈ (fℚ[a, n + 1]).rootSet (AlgebraicClosure ℚ) ↔
    β ^ 2 + (a : AlgebraicClosure ℚ) ∈ (fℚ[a, n]).rootSet (AlgebraicClosure ℚ) := by
  rw [mem_rootSet, mem_rootSet, and_iff_right (monic_map_iteratedPoly a _).ne_zero,
    and_iff_right (monic_map_iteratedPoly a _).ne_zero, map_iteratedPoly_succ, aeval_comp]
  simp

/-- Any `ℚ`-automorphism of `ℚ̄` raised to the power `2 ^ m` fixes every root of `f_m`. -/
theorem pow_two_pow_apply_root (ϕ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    {m : ℕ} {γ : AlgebraicClosure ℚ} (hγ : γ ∈ (fℚ[a, m]).rootSet (AlgebraicClosure ℚ)) :
    (ϕ ^ (2 ^ m)) γ = γ := by
  induction m generalizing γ with
  | zero =>
    rw [iteratedPoly_zero, map_X,
      mem_rootSet_of_injective (algebraMap ℚ (AlgebraicClosure ℚ)).injective X_ne_zero] at hγ
    obtain rfl : γ = 0 := by simpa using hγ
    simp
  | succ k ih =>
    have hsq : ((ϕ ^ 2 ^ k) γ) ^ 2 = γ ^ 2 := by
      have hfix := ih ((mem_rootSet_iteratedPoly_succ a k γ).mp hγ)
      have hmap : (ϕ ^ 2 ^ k) (γ ^ 2 + (a : AlgebraicClosure ℚ))
          = ((ϕ ^ 2 ^ k) γ) ^ 2 + (a : AlgebraicClosure ℚ) := by
        simp [map_add, map_pow, map_intCast]
      rw [hmap] at hfix
      linear_combination hfix
    rw [show (2 : ℕ) ^ (k + 1) = 2 ^ k + 2 ^ k by ring, pow_add, AlgEquiv.mul_apply]
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h
    · rw [h, h]
    · rw [h, map_neg, h, neg_neg]

/-- `Ω_n = Gal(f_n/ℚ)` is a 2-group. -/
theorem isPGroup_galoisGroup (n : ℕ) : IsPGroup 2 (GaloisGroup a n) := by
  set F := fℚ[a, n]
  refine isPGroup_iff_pow_pow_eq_one.mpr fun σ ↦ ⟨n, ?_⟩
  obtain ⟨ϕ, rfl⟩ := Gal.restrict_surjective F (AlgebraicClosure ℚ) σ
  apply Gal.galActionHom_injective F (AlgebraicClosure ℚ)
  rw [map_pow, map_one, ← map_pow, ← map_pow]
  ext β
  simp only [Equiv.Perm.one_apply]
  exact (Gal.galActionHom_restrict F (AlgebraicClosure ℚ) (ϕ ^ 2 ^ n) β).trans
    (pow_two_pow_apply_root a ϕ β.2)

/-- Odoni's embedding theorem: `Ω_n` embeds into `[C_2]^n`, being a `2`-group acting faithfully on
the at most `2 ^ n` roots of `f_n`. -/
theorem odoni_embedding (n : ℕ) :
    ∃ φ : GaloisGroup a n →* WreathPower n, Function.Injective φ :=
  (isPGroup_galoisGroup a n).exists_injective_monoidHom_iteratedWreathProduct
    (Gal.galActionHom_injective (fℚ[a, n]) (AlgebraicClosure ℚ))
    ((Nat.card_coe_set_eq _).trans_le (ncard_rootSet_iteratedPoly_le a n))
    (Multiplicative (ZMod 2)) (by simp [Nat.card_eq_fintype_card])

/-- Every element of `ℚ̄` has a square root after subtracting `a`; the square roots of the
`α - a` for `α` a root of `f_n` are what generates `K_{n+1}` over `K_n`. -/
lemma exists_sq_eq_sub (α : AlgebraicClosure ℚ) :
    ∃ β : AlgebraicClosure ℚ, β ^ 2 = α - (a : AlgebraicClosure ℚ) :=
  IsAlgClosed.exists_pow_nat_eq _ two_pos

lemma splittingField_le_succ (n : ℕ) : splittingField a n ≤ splittingField a (n + 1) := by
  refine IntermediateField.adjoin_le_iff.mpr fun α hα ↦ ?_
  obtain ⟨β, hβ⟩ := exists_sq_eq_sub a α
  have hβmem : β ∈ splittingField a (n + 1) :=
    IntermediateField.subset_adjoin ℚ _ ((mem_rootSet_iteratedPoly_succ a n β).mpr
      (by simpa [hβ, sub_add_cancel] using hα))
  have hα_eq : α = β ^ 2 + (a : AlgebraicClosure ℚ) := by rw [hβ]; ring
  rw [hα_eq]
  exact add_mem (pow_mem hβmem 2) (IntermediateField.intCast_mem _ a)

lemma splittingField_mono {m n : ℕ} (hmn : m ≤ n) : splittingField a m ≤ splittingField a n :=
  Nat.le_induction le_rfl (fun k _ ih ↦ ih.trans (splittingField_le_succ a k)) n hmn

/-- `K_0 = ℚ`: the only root of `f_0 = X` is `0`. -/
@[simp] lemma splittingField_zero_eq_bot : splittingField a 0 = ⊥ := by
  refine IntermediateField.adjoin_eq_bot_iff.mpr fun x hx ↦ ?_
  rw [iteratedPoly_zero, map_X, mem_rootSet_of_injective
    (algebraMap ℚ (AlgebraicClosure ℚ)).injective X_ne_zero] at hx
  rw [SetLike.mem_coe, show x = 0 by simpa using hx]
  exact zero_mem _

end

section

variable (a : ℤ)

/-! ### The Kummer tower `K_n ⊆ K_{n+1}` -/

/-- `K_{n+1} = K_n(√(α - a) : α root of f_n)`, for any choice `g` of square roots: a root `β` of
`f_{n+1}` is `± g(β² + a)`, and `g α` is a root of `f_{n+1}` for every root `α` of `f_n`. -/
theorem splittingField_succ_eq_sup_adjoin (n : ℕ) (g : AlgebraicClosure ℚ → AlgebraicClosure ℚ)
    (hg : ∀ α, g α ^ 2 = α - (a : AlgebraicClosure ℚ)) :
    splittingField a (n + 1) = splittingField a n ⊔
      IntermediateField.adjoin ℚ (g '' ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ))) := by
  refine le_antisymm (IntermediateField.adjoin_le_iff.mpr fun β hβ ↦ ?_)
    (sup_le (splittingField_le_succ a n) (IntermediateField.adjoin_le_iff.mpr ?_))
  · have hgmem : g (β ^ 2 + a) ∈
        IntermediateField.adjoin ℚ (g '' ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ))) :=
      IntermediateField.subset_adjoin ℚ _ ⟨_, (mem_rootSet_iteratedPoly_succ a n β).mp hβ, rfl⟩
    have hsq : β ^ 2 = g (β ^ 2 + a) ^ 2 := by rw [hg, add_sub_cancel_right]
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h
    · exact h ▸ SetLike.le_def.mp le_sup_right hgmem
    · exact h ▸ neg_mem (SetLike.le_def.mp le_sup_right hgmem)
  · intro x ⟨α, hα, hx⟩
    exact hx ▸ IntermediateField.subset_adjoin ℚ _
      ((mem_rootSet_iteratedPoly_succ a n (g α)).mpr (by rwa [hg α, sub_add_cancel]))

/-- The square of a root of `f_{n+1}` lies in `K_n`: `K_n ⊆ K_{n+1}` is a `2`-Kummer extension. -/
lemma sq_mem_splittingField_of_mem_rootSet_succ {n : ℕ} {β : AlgebraicClosure ℚ}
    (hβ : β ∈ (fℚ[a, n + 1]).rootSet (AlgebraicClosure ℚ)) : β ^ 2 ∈ splittingField a n := by
  rw [← add_sub_cancel_right (β ^ 2) (a : AlgebraicClosure ℚ)]
  exact sub_mem
    (IntermediateField.subset_adjoin ℚ _ ((mem_rootSet_iteratedPoly_succ a n β).mp hβ))
    (IntermediateField.intCast_mem _ a)

/-- The relative degree `[K_{n+1} : K_n]` is the degree of the multiquadratic extension of `K_n`
generated by a choice `g` of square roots of the `α - a`, `α` a root of `f_n`. -/
theorem relfinrank_succ_eq_finrank_adjoin (n : ℕ) (g : AlgebraicClosure ℚ → AlgebraicClosure ℚ)
    (hg : ∀ α, g α ^ 2 = α - (a : AlgebraicClosure ℚ)) :
    (splittingField a n).relfinrank (splittingField a (n + 1))
      = Module.finrank ↥(splittingField a n)
          ↥(IntermediateField.adjoin ↥(splittingField a n)
            (g '' ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)))) := by
  rw [splittingField_succ_eq_sup_adjoin a n g hg,
    ← IntermediateField.restrictScalars_adjoin_eq_sup, IntermediateField.relfinrank_eq_finrank_of_le
      (by rw [IntermediateField.restrictScalars_adjoin_eq_sup]; exact le_sup_left)]
  congr 1

lemma relfinrank_succ_le (n : ℕ) :
    (splittingField a n).relfinrank (splittingField a (n + 1)) ≤ 2 ^ 2 ^ n := by
  choose g hg using exists_sq_eq_sub a
  rw [relfinrank_succ_eq_finrank_adjoin a n g hg]
  refine (IntermediateField.finrank_adjoin_sqrt_le_two_pow_ncard ((rootSet_finite _ _).image g)
    ?_).trans (Nat.pow_le_pow_right two_pos
      ((Set.ncard_image_le (rootSet_finite _ _)).trans (ncard_rootSet_iteratedPoly_le a n)))
  intro x ⟨α, hα, hx⟩
  exact ⟨⟨α - a, sub_mem (IntermediateField.subset_adjoin ℚ _ hα)
    (IntermediateField.intCast_mem _ a)⟩, hx ▸ hg α⟩

lemma card_wreathPower (n : ℕ) : Nat.card (WreathPower n) = 2 ^ (2 ^ n - 1) := by
  rw [IteratedWreathProduct.card,
    show Nat.card (Multiplicative (ZMod 2)) = 2 by simp [Nat.card_eq_fintype_card],
    Nat.geomSum_eq le_rfl]
  norm_num

/-- `#[C_2]^{n+1} = #[C_2]^n · 2^{2^n}`. -/
lemma card_wreathPower_succ (n : ℕ) :
    Nat.card (WreathPower (n + 1)) = Nat.card (WreathPower n) * 2 ^ 2 ^ n := by
  rw [card_wreathPower, card_wreathPower, ← pow_add]
  congr 1
  have := Nat.one_le_two_pow (n := n)
  rw [pow_succ]
  lia

lemma card_galoisGroup_eq_finrank (n : ℕ) :
    Nat.card (GaloisGroup a n) = Module.finrank ℚ (splittingField a n) :=
  (Nat.card_congr (AlgEquiv.autCongr (IsSplittingField.algEquiv _ (fℚ[a, n])).symm).toEquiv).trans
    (IsGalois.card_aut_eq_finrank ℚ _)

/-- Lemma 1.4: `Ω_{n+1} ≅ [C_2]^{n+1}` iff `Ω_n ≅ [C_2]^n` and `[K_{n+1} : K_n] = 2^{2^n}`. Both
`#Ω_n ≤ #[C_2]^n` (by `odoni_embedding`) and `[K_{n+1} : K_n] ≤ 2^{2^n}`, and the products of the
two sides agree iff both factors do. -/
theorem nonempty_mulEquiv_succ_iff (n : ℕ) :
    Nonempty (GaloisGroup a (n + 1) ≃* WreathPower (n + 1)) ↔
      Nonempty (GaloisGroup a n ≃* WreathPower n) ∧
        (splittingField a n).relfinrank (splittingField a (n + 1)) = 2 ^ 2 ^ n := by
  obtain ⟨φn, hφn⟩ := odoni_embedding a n
  obtain ⟨φn1, hφn1⟩ := odoni_embedding a (n + 1)
  rw [φn1.nonempty_mulEquiv_iff_card_eq hφn1, φn.nonempty_mulEquiv_iff_card_eq hφn,
    card_wreathPower_succ, card_galoisGroup_eq_finrank a (n + 1),
    ← IntermediateField.finrank_bot_mul_relfinrank (splittingField_le_succ a n),
    ← card_galoisGroup_eq_finrank]
  exact mul_eq_mul_iff_eq_and_eq_of_pos
    (Nat.le_of_dvd Nat.card_pos (Subgroup.card_dvd_of_injective φn hφn)) (relfinrank_succ_le a n)
    Nat.card_pos (Nat.two_pow_pos _)

end

end QuadraticIterates
